name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 12:00 AM UTC (Adjust for your timezone)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
          git config --global user.name "rktoshavat"
          git config --global user.email "tumhari-email@example.com"

      - name: Update File and Commit
        run: |
          echo "$(date)" >> daily_commit.txt
          git add .
          git commit -m "Daily commit - $(date)"
          git push
